hasher: {}

redis:
  image:
    repository: redis
    tag: latest
  service:
    port: 6379
  readinessProbe:
    tcpSocket:
      port: 6379
rng:
  readinessProbe: false
webui:
  service:
    type: NodePort
worker:
  service: false
