---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dockercoins-umbrella
  namespace: flux-system
spec:
  chart:
    spec:
      chart: exercice-umbrella-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  releaseName: dockercoins
  targetNamespace: dockercoins-umbrella
---
apiVersion: v1
kind: Namespace
metadata:
  name: dockercoins-umbrella
